### ISSUE TITLE
Run  test failed on MySQL

### ISSUE THREAD

**Issue by shenli** [go-xorm/tests#14]
@lunny We test tidb with the lastest go-xorm but get error.  And then we use MySQL for test but get the same error. So I think there maybe something wrong.

**MySQL Version:**
mysql  Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Run CMD:**
➜  mysql git:(master) ✗ pwd
/home/shenli/go/src/github.com/go-xorm/tests/mysql
➜  mysql git:(master) ✗ sh ./mysql.sh 

**Error Message:**
[xorm] [info]  2016/05/23 15:25:44.197899 [sql] SELECT `message`.`id`, `message`.`type_id`, `message`.`title`, `message`.`content`, `message`.`uid`, `message`.`to_uid`, `message`.`create_time`, `message`.`id`, `message`.`name`, `message`.`id`, `message`.`name`, `message`.`id`, `message`.`name` FROM `message` LEFT JOIN `message_user` AS `sender` ON `sender`.`id`=`message`.`uid` LEFT JOIN `message_user` AS `receiver` ON `receiver`.`id`=`message`.`to_uid` LEFT JOIN `message_type` AS `type` ON `type`.`id`=`message`.`id`
--- FAIL: TestMysql (1.29s)
    testExtends.go:368: Error 1054: Unknown column 'message.name' in 'field list'
panic: Error 1054: Unknown column 'message.name' in 'field list' [recovered]
    panic: Error 1054: Unknown column 'message.name' in 'field list'

goroutine 5 [running]:
panic(0x89d660, 0xc8201546e0)
    /home/shenli/software/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc820094510)
    /home/shenli/software/go/src/testing/testing.go:467 +0x192
panic(0x89d660, 0xc8201546e0)
    /home/shenli/software/go/src/runtime/panic.go:426 +0x4e9
github.com/go-xorm/tests.testExtends3(0xc820146000, 0xc820094510)
    /home/shenli/go/src/github.com/go-xorm/tests/testExtends.go:369 +0x1818
github.com/go-xorm/tests.testExtends(0xc820146000, 0xc820094510)
    /home/shenli/go/src/github.com/go-xorm/tests/testExtends.go:214 +0x4421
github.com/go-xorm/tests.BaseTestAll2(0xc820146000, 0xc820094510)
    /home/shenli/go/src/github.com/go-xorm/tests/base.go:666 +0x63a
github.com/go-xorm/tests/mysql.TestMysql(0xc820094510)
    /home/shenli/go/src/github.com/go-xorm/tests/mysql/mysql_test.go:43 +0x4b1
testing.tRunner(0xc820094510, 0xb6baa0)
    /home/shenli/software/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /home/shenli/software/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL    github.com/go-xorm/tests/mysql  1.297s

**Comment by gavv** [comment]
It's after go-xorm/xorm#387 + [this commit](https://github.com/go-xorm/xorm/commit/5aedd09131cda773f223d5e1576e3b4c4545661b).

go-xorm/xorm#398 should fix it.

**Comment by lunny** [comment]
I think this has been resolved.
