### ISSUE TITLE
Please Provide Annotated Release Tags

### ISSUE THREAD

**Issue by MTecknology** [go-xorm/tests#17]
This package is used by Gitea which is a package I'm currently working to get into Debian. This means I get to do a review of all build dependencies. While working through your project, I saw that tags are used to mark releases, but they are not being annotated.

Unannotated release tags end up causing some headaches for packaging systems that monitor upstream activity--mostly for new releases--because the information is missing from 'git describe'. To annotate a tag, it just needs the -a flag passed. (git tag -a).

If you're willing to, it's possible to update the current tags (or just latest) with annotation. I've included some links [1] [2] that explain the process.

If you choose not to update tags, it would still be hugely appreciated if you could use annotated tags in the future.

[1] http://sartak.org/2011/01/replace-a-lightweight-git-tag-with-an-annotated-tag.html
[2] http://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag

**Comment by lunny** [comment]
Hi, maybe you mean `github.com/go-xorm/xorm`? This is a test repository for xorm and should be not a dependency by xorm or Gitea.

**Comment by MTecknology** [comment]
Nope, I meant xorm-test. I haven't had a chance to get to look at xorm yet because xorm-test is a build dependency of xorm (for running tests).

**Comment by lunny** [comment]
I have added one, but I don't know if it's help for you.

**Comment by MTecknology** [comment]
Yup! It helps! It's always helpful when release tags are annotated, even if it's just "v${version}". Thanks!

**Comment by MTecknology** [comment]
I'm assuming we'll continue with this practice so this issue is resolved.
